-- Basic

-- List all unique product categories in the dataset.

-- Show the number of products in each product category.

-- What is the average rating for each brand?

-- Retrieve all products with a rating greater than 4.0.

-- Show products with a discount greater than 50%.

-- Intermediate
-- 6. List top 5 brands with the highest number of products.
-- 7. What is the total revenue generated by each brand?
-- 8. What is the average discount percentage by product category?
-- 9. Find the product with the highest revenue.
-- 10. List products where the discounted price is less than ₹500.

-- Aggregations
-- 11. What is the total number of ratings received by each category?
-- 12. Which brand has the highest average rating_count per product?
-- 13. Show average marked price and discounted price per category.
-- 14. Find the top 5 highest discounted products (in %).
-- 15. What is the total revenue from products with rating above 4.2?

-- Advanced (CTE, Ranking, Windows)
-- 16. Use a CTE to find top 3 products by revenue in each category.
-- 17. Rank products within each brand based on revenue.
-- 18. Calculate cumulative revenue per category.
-- 19. Which category has the highest average discount percent?
-- 20. What is the average rating for top 3 most selling products by rating_count?

-- Business insights
-- 21. Identify brands that have an average rating below 3.5.
-- 22. Determine the top 3 categories contributing the most to total revenue.
-- 23. List brands where more than 75% of products have a discount above 40%.
-- 24. Which category has the most expensive product (marked price)?
-- 25. Calculate revenue per rating point for each product (i.e., revenue/rating_count).

